services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/app:cached
    command: sleep infinity
    env_file:
      - ../.env
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 1024M

  db:
    image: postgres:15
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Remove port exposure for security
    # ports:
    #   - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

volumes:
  pgdata:
